### PR TITLE
Remove polyfill for Linking.openSettings on iOS

### PR DESCRIPTION
**Pull request by lukmccall**
Follow up from https://github.com/expo/expo/pull/7717

### CODE REVIEW

**Comment by brentvatne** [comment]
let's not merge this in to sdk-37 branch - we can keep using the polyfill for sdk-37 and instead just use this code in sdk-38+

**Comment by ide** [comment]
If we're not looking to make changes to SDK 37 and want the changes to apply to SDK 38 and onwards, this should go on master (and if the sdk-38 branch had been cut, then that branch too, but that's not the case right now).

**Comment by lukmccall** [comment]
@brentvatne, @ide I need more clarification. I was aware of that we don't want to apply this to branch SDK-37. However, I wasn't sure where it should be merged. 

So, if this change was only made on the branch SDK-37, that means it won't be applied to the future SDK-38 branch? Moreover, the `master` branch looks like it's not up to date. As well as the `SDK-master` branch.

**Comment by ide** [comment]
Oh, sorry, I thought this was the expo repo. If we want this change to apply to sdk-38, which doesn't have the polyfill anyway, then we need to remember not to cherry-pick the commit that added the polyfill when we're creating the sdk-38 branch. (This is why cherry-picked commits are so expensive.)

**Comment by ide** [comment]
In short, I think we don't need to merge this PR to any branch, but we do need to remember this change when making the sdk-38 branch.

**Comment by brentvatne** [comment]
ok let's just leave it open then!

**Pull request closed without merging**
