### PR TITLE
Reapply expo fixes with respect to bare workflow

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why 

Fixes https://github.com/expo/expo/issues/6262.

# How

- reformatted changes from https://github.com/expo/react-native/commit/sdk-36 so that [the compare between commits](https://github.com/expo/react-native/compare/sdk-36~1..sdk-36-bare~3) looks as small as possible
- reverted changes that will be done by `ReactAndroidCodeTransformer` when we import `react-native-lab` to `android` https://github.com/expo/react-native/pull/20/commits/6f62ba22249393b7b0dbb090df1b6770c091eb7c
- prepared `react-native-lab` for `bare-expo` and for `ReactAndroidCodeTransformer` by (https://github.com/expo/react-native/pull/20/commits/3ba4045211fd1923a237e519b28dace3d737cd50):
  - extracting `getExponentActivityId` so `ReactAndroidCodeTransformer` can replace the `-1` with access to `mDevSettings.mSettings.exponentActivityId` which is added and exposed only by the transformer
  - reloading JS if expo-reloading fails (this would happen in `bare-expo`, what we want to do then is to just reload JS)
- instead of commenting out stuff right in `react-native-lab`, I added labels to statements that should be removed so that `ReactAndroidCodeTransformer` deletes them when importing to `expo` repo. https://github.com/expo/react-native/pull/20/commits/4c65ae2dcdd1b7356e9d8e5621fe12f6b08c6612

### CODE REVIEW

**Comment by sjchmiela** [comment]
Ideally this pull request would be squashed into Brent's https://github.com/expo/react-native/commit/ce1bf40f6a01fcdf346884eb5fdaa39929f609d4.

In my opinion the most readable way to review this PR is to look at the diff between last-but-one commit from `sdk-36` and HEAD of this branch: https://github.com/expo/react-native/compare/sdk-36~1..sdk-36-bare This way we can verify that Brent's changes will be properly applied and `ReactAndroid` won't break in bare.

**Comment by sjchmiela** [comment]
The identation changes were introduced in ce1bf40, when code transformed by `ReactAndroidCodeTransformer` ended up here. This PR reverts those indentation changes, resulting with equally-big-diff. That’s why I suggested:

> In my opinion the most readable way to review this PR is to look at the diff between last-but-one commit from sdk-36 and HEAD of this branch: https://github.com/expo/react-native/compare/sdk-36~1..sdk-36-bare This way we can verify that Brent's changes will be properly applied and ReactAndroid won't break in bare.

**Comment by ide** [comment]
@sjchmiela Could you merge this, and then (on your computer) do an interactive rebase and re-order + squash commits (and then force-push) so our commit history is clean again? 🙏

**Comment by sjchmiela** [comment]
Oh, actually, I already did this! Sorry for forgetting to close this, I think I may have hoped it will be automatically closed by GitHub.

Left two commits out of those few:

- cleaned up [[android] Always reload from manifest expo/expo#6134](https://github.com/expo/react-native/commit/d8f3fbef53dc53f94dc08b7476b0fc5f15b7771b)
- [[android] Prepare ReactAndroid for bare and :tools:execute](https://github.com/expo/react-native/commit/ae5e396b37a0d21b2dfe578502f738c9f537f1d1)

**Pull request closed without merging**
