### PR TITLE
SDK 34.0.1 Hotfix

### PR DESCRIPTION
**Pull request by mjgallag**
@esamelson FYI, you may want to consider backporting these iOS 13 crash fixes to SDK 34. We're using this fork to avoid rushing to SDK 35 immediately and I confirm it fixes nasty fishhook issue. Thanks!

### CODE REVIEW

**Comment by esamelson** [comment]
@mjgallag - are you experiencing these crashes with SDK 34 on the current public version of iOS 13? Thus far we've only seen reports of fishhook causing crashes on the iOS 13.1 beta.

**Comment by mjgallag** [comment]
@esamelson based on reports coming in from our users we believe this issue affects currently public iOS 13.0 but only newer devices (iPhone XS, iPhone XR) causing apps to crash immediately upon opening. Sadly we don't own any of these devices ourselves, perhaps we should buy one :) We also cannot seem to reproduce in simulator.

**Comment by esamelson** [comment]
ahh that clarifies things a lot. Thanks very much for that info. We'll go ahead and backport this to 34 and 33 and make an announcement later today.

**Comment by mjgallag** [comment]
@esamelson thanks, note that our crash reporting doesn't catch it either because app never gets far enough to send it to us.

**Pull request merged**
